# Generated by Django 5.1.4 on 2025-01-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duttaEcommerceapp', '0003_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField()),
                ('challenges', models.TextField()),
                ('achievements', models.TextField()),
            ],
        ),
    ]
