# Generated by Django 5.1.4 on 2025-01-21 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duttaEcommerceapp', '0004_jobseekeruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_seeker_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='duttaEcommerceapp.jobseekeruser')),
            ],
        ),
    ]
