# Generated by Django 5.1.4 on 2025-01-21 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duttaEcommerceapp', '0005_jobseekercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekeruser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
