# Generated by Django 5.1.4 on 2025-01-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duttaEcommerceapp', '0006_jobseekeruser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekeruser',
            name='relax',
            field=models.TextField(blank=True, null=True),
        ),
    ]
