# Generated by Django 5.1.4 on 2025-01-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duttaEcommerceapp', '0007_jobseekeruser_relax'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
