# Site settings
title: "DuttaTechEcommSphere"
description: "Empowering Future of eCommerce Through Technological Synergy"
baseurl: "" # the subpath of your site, e.g. "/blog"
url: "https://duttatechecommsphere.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

# Excludes these files and folders from being processed
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalinks
permalink: /:categories/:year/:month/:day/:title/

# Additional configuration options
paginate: 5
paginate_path: "/page:num/"
