name: Deploy Django App

on:
  push:
    branches:
      - updated-project
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Miniconda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
          bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda3
          export PATH="$HOME/miniconda3/bin:$PATH"
          conda init
          echo "Miniconda installed and PATH updated."

      - name: Create and activate virtual environment
        run: |
          source $HOME/miniconda3/etc/profile.d/conda.sh
          conda create -n myenv python=3.8 -y
          source activate myenv
          conda info --envs
          if [ $? -ne 0 ]; then
            echo "Failed to create or activate virtual environment"
            exit 1
          fi
          echo "Virtual environment created and activated."

      - name: Install dependencies
        run: |
          source $HOME/miniconda3/etc/profile.d/conda.sh
          source activate myenv
          pip install -r requirements.txt
          if [ $? -ne 0 ]; then
            echo "Failed to install dependencies"
            exit 1
          fi
          echo "Dependencies installed."

      - name: Set Environment Variables
        run: |
          echo "PYTHONPATH=${{ github.workspace }}/public_html" >> $GITHUB_ENV
          echo "DJANGO_SETTINGS_MODULE=duttaEcommerceproject.settings" >> $GITHUB_ENV
          echo "DATABASE_ENGINE=django.db.backends.sqlite3" >> $GITHUB_ENV
          echo "DATABASE_NAME=${{ github.workspace }}/public_html/db
